[run]
init_cmds = [
	["go", "run", "make.go", "bindata", "build"],
	["./gitea", "web"]
]

watch_all = true

watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers",
	"$WORKDIR/static"
]

watch_exts = [
	".go",
	".ini"
]

ignore = [
	"vendor",
	"bindata"
]

cmds = [
	["go", "run", "make.go", "bindata", "build"],
	["./website", "web"]
]

build_delay = 1500
