language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

sudo: false

script: go build -v

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

    urls:
      - https://webhooks.gitter.im/e/cac0161488e4bf1fb94b
