sudo: false
language: go

go:
  - 1.5
  - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TAGS=cert,pam,sqlite

addons:
  apt:
    packages:
      - libpam0g-dev

install:
  - echo "Skip the default install!"

script:
  - go run make.go deps build test clean

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

    urls:
      - https://webhooks.gitter.im/e/cac0161488e4bf1fb94b
